name: Generate Articles

on:
  push:
    paths:
      - "articlesText/**"
      - "templates/base.html"
      - "build.js"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate HTML
        run: npm run generate

      - name: Commit and push generated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add articles
          git commit -m "Auto-generate articles" || echo "No changes"
          git push origin main
